baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Cranberry-CTF 手册'
theme = 'hugo-book'

[markup.highlight]
  style = 'github'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true